name: Deploy Maven Artifact on Release

on:
  create:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Maven Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Extract and format release version
        id: extract_version
        run: |
          TAG_VERSION=${{ github.ref_name }}
          echo "ARTIFACT_VERSION=${TAG_VERSION:1}" >> $GITHUB_ENV

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          export GPG_TTY=$(tty)
          # Install gpg secret key
          cat <(echo -e "${{ secrets.MAVEN_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      - name: Build and deploy artifact
        env:
          MAVEN_OPTS: >-
            -Dserver.id=${{ secrets.MAVEN_ID }}
            -Dserver.username=${{ secrets.MAVEN_USERNAME }}
            -Dserver.password=${{ secrets.MAVEN_PASSWORD }}
        run: |
          mvn clean deploy \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }} \
          -DskipTests=true \
          -Dartifact.version=${{ env.ARTIFACT_VERSION }} \
          
          
