name: Deploy Maven Artifact on Release

on:
  create:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Maven Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ${{ secrets.MAVEN_ID }}
          server-username: ${{ secrets.MAVEN_USERNAME }}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}
      - name: Extract and format release version
        id: extract_version
        run: |
          TAG=${{ github.ref_name }}
          echo "ARTIFACT_VERSION=${TAG:1}" >> $GITHUB_ENV
      - name: Publish package
        run: mvn clean --batch-mode deploy -DskipTests -Dartifact.version=${{ env.ARTIFACT_VERSION }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_SECRET_KEY_PASSWORD }}
          
          
